// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package lib

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type FuzzyRequest struct {
	Qry                  string   `protobuf:"bytes,1,opt,name=qry" json:"qry,omitempty"`
	Cid                  string   `protobuf:"bytes,2,opt,name=cid" json:"cid,omitempty"`
	Algo                 string   `protobuf:"bytes,3,opt,name=algo" json:"algo,omitempty"`
	Max                  int32    `protobuf:"varint,4,opt,name=max" json:"max,omitempty"`
	Data                 []string `protobuf:"bytes,5,rep,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FuzzyRequest) Reset()         { *m = FuzzyRequest{} }
func (m *FuzzyRequest) String() string { return proto.CompactTextString(m) }
func (*FuzzyRequest) ProtoMessage()    {}
func (*FuzzyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_6f1cf8b94412cbfc, []int{0}
}
func (m *FuzzyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FuzzyRequest.Unmarshal(m, b)
}
func (m *FuzzyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FuzzyRequest.Marshal(b, m, deterministic)
}
func (dst *FuzzyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FuzzyRequest.Merge(dst, src)
}
func (m *FuzzyRequest) XXX_Size() int {
	return xxx_messageInfo_FuzzyRequest.Size(m)
}
func (m *FuzzyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FuzzyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FuzzyRequest proto.InternalMessageInfo

func (m *FuzzyRequest) GetQry() string {
	if m != nil {
		return m.Qry
	}
	return ""
}

func (m *FuzzyRequest) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *FuzzyRequest) GetAlgo() string {
	if m != nil {
		return m.Algo
	}
	return ""
}

func (m *FuzzyRequest) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *FuzzyRequest) GetData() []string {
	if m != nil {
		return m.Data
	}
	return nil
}

// The response message containing the greetings
type FuzzyReply struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Match                []string `protobuf:"bytes,3,rep,name=match" json:"match,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FuzzyReply) Reset()         { *m = FuzzyReply{} }
func (m *FuzzyReply) String() string { return proto.CompactTextString(m) }
func (*FuzzyReply) ProtoMessage()    {}
func (*FuzzyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_6f1cf8b94412cbfc, []int{1}
}
func (m *FuzzyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FuzzyReply.Unmarshal(m, b)
}
func (m *FuzzyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FuzzyReply.Marshal(b, m, deterministic)
}
func (dst *FuzzyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FuzzyReply.Merge(dst, src)
}
func (m *FuzzyReply) XXX_Size() int {
	return xxx_messageInfo_FuzzyReply.Size(m)
}
func (m *FuzzyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FuzzyReply.DiscardUnknown(m)
}

var xxx_messageInfo_FuzzyReply proto.InternalMessageInfo

func (m *FuzzyReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *FuzzyReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *FuzzyReply) GetMatch() []string {
	if m != nil {
		return m.Match
	}
	return nil
}

func init() {
	proto.RegisterType((*FuzzyRequest)(nil), "lib.FuzzyRequest")
	proto.RegisterType((*FuzzyReply)(nil), "lib.FuzzyReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FuzzyClient is the client API for Fuzzy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FuzzyClient interface {
	// Sends a greeting
	Match(ctx context.Context, in *FuzzyRequest, opts ...grpc.CallOption) (*FuzzyReply, error)
}

type fuzzyClient struct {
	cc *grpc.ClientConn
}

func NewFuzzyClient(cc *grpc.ClientConn) FuzzyClient {
	return &fuzzyClient{cc}
}

func (c *fuzzyClient) Match(ctx context.Context, in *FuzzyRequest, opts ...grpc.CallOption) (*FuzzyReply, error) {
	out := new(FuzzyReply)
	err := c.cc.Invoke(ctx, "/lib.Fuzzy/Match", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Fuzzy service

type FuzzyServer interface {
	// Sends a greeting
	Match(context.Context, *FuzzyRequest) (*FuzzyReply, error)
}

func RegisterFuzzyServer(s *grpc.Server, srv FuzzyServer) {
	s.RegisterService(&_Fuzzy_serviceDesc, srv)
}

func _Fuzzy_Match_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FuzzyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FuzzyServer).Match(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lib.Fuzzy/Match",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FuzzyServer).Match(ctx, req.(*FuzzyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Fuzzy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lib.Fuzzy",
	HandlerType: (*FuzzyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Match",
			Handler:    _Fuzzy_Match_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_6f1cf8b94412cbfc) }

var fileDescriptor_api_6f1cf8b94412cbfc = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xc1, 0x4a, 0xc5, 0x30,
	0x10, 0x45, 0xad, 0x69, 0x84, 0x0e, 0x82, 0x1a, 0x5c, 0x04, 0x57, 0xa5, 0xab, 0x6e, 0xec, 0x42,
	0xc1, 0x4f, 0x10, 0x37, 0x6e, 0xf2, 0x07, 0x69, 0x52, 0x6a, 0x20, 0x25, 0x69, 0x9b, 0x82, 0xe9,
	0xd7, 0x3f, 0x66, 0xfa, 0x1e, 0x74, 0x77, 0xe6, 0x70, 0xb9, 0x97, 0x81, 0x4a, 0x47, 0xd7, 0xc5,
	0x25, 0xa4, 0x20, 0x98, 0x77, 0x7d, 0xe3, 0xe1, 0xf1, 0x7b, 0xdb, 0xf7, 0xac, 0x86, 0x79, 0x1b,
	0xd6, 0x24, 0x9e, 0x81, 0xcd, 0x4b, 0x96, 0x45, 0x5d, 0xb4, 0x95, 0x42, 0x44, 0x63, 0x9c, 0x95,
	0xf7, 0x87, 0x31, 0xce, 0x0a, 0x01, 0xa5, 0xf6, 0x63, 0x90, 0x8c, 0x14, 0x31, 0xa6, 0x26, 0xfd,
	0x2f, 0xcb, 0xba, 0x68, 0xb9, 0x42, 0xc4, 0x94, 0xd5, 0x49, 0x4b, 0x5e, 0x33, 0x4c, 0x21, 0x37,
	0x3f, 0x00, 0xd7, 0xb5, 0xe8, 0x33, 0x26, 0x4c, 0xb0, 0x03, 0x8d, 0x71, 0x45, 0x4c, 0x3d, 0xeb,
	0x78, 0x5b, 0x9b, 0xd6, 0x51, 0xbc, 0x02, 0x9f, 0x74, 0x32, 0x7f, 0x92, 0x51, 0xd1, 0x71, 0x7c,
	0x7c, 0x01, 0xa7, 0x26, 0xf1, 0x0e, 0xfc, 0x17, 0x8d, 0x78, 0xe9, 0xbc, 0xeb, 0xbb, 0xf3, 0x33,
	0x6f, 0x4f, 0x67, 0x15, 0x7d, 0x6e, 0xee, 0xfa, 0x07, 0xfa, 0xfd, 0xf3, 0x12, 0x00, 0x00, 0xff,
	0xff, 0x79, 0xf2, 0xd4, 0x82, 0x08, 0x01, 0x00, 0x00,
}
