# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import api_pb2 as api__pb2


class FuzzyStub(object):
  """The fuzzy match service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Match = channel.unary_unary(
        '/lib.Fuzzy/Match',
        request_serializer=api__pb2.FuzzyRequest.SerializeToString,
        response_deserializer=api__pb2.FuzzyReply.FromString,
        )


class FuzzyServicer(object):
  """The fuzzy match service definition.
  """

  def Match(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FuzzyServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Match': grpc.unary_unary_rpc_method_handler(
          servicer.Match,
          request_deserializer=api__pb2.FuzzyRequest.FromString,
          response_serializer=api__pb2.FuzzyReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'lib.Fuzzy', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
