# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='lib',
  syntax='proto3',
  serialized_pb=_b('\n\tapi.proto\x12\x03lib\"Q\n\x0c\x46uzzyRequest\x12\x0b\n\x03qry\x18\x01 \x01(\t\x12\x0b\n\x03\x63id\x18\x02 \x01(\t\x12\x0c\n\x04\x61lgo\x18\x03 \x01(\t\x12\x0b\n\x03max\x18\x04 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x05 \x03(\t\"6\n\nFuzzyReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\r\n\x05match\x18\x03 \x03(\t26\n\x05\x46uzzy\x12-\n\x05Match\x12\x11.lib.FuzzyRequest\x1a\x0f.lib.FuzzyReply\"\x00\x62\x06proto3')
)




_FUZZYREQUEST = _descriptor.Descriptor(
  name='FuzzyRequest',
  full_name='lib.FuzzyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='qry', full_name='lib.FuzzyRequest.qry', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cid', full_name='lib.FuzzyRequest.cid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='algo', full_name='lib.FuzzyRequest.algo', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max', full_name='lib.FuzzyRequest.max', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='lib.FuzzyRequest.data', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=99,
)


_FUZZYREPLY = _descriptor.Descriptor(
  name='FuzzyReply',
  full_name='lib.FuzzyReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='lib.FuzzyReply.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='lib.FuzzyReply.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='match', full_name='lib.FuzzyReply.match', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['FuzzyRequest'] = _FUZZYREQUEST
DESCRIPTOR.message_types_by_name['FuzzyReply'] = _FUZZYREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FuzzyRequest = _reflection.GeneratedProtocolMessageType('FuzzyRequest', (_message.Message,), dict(
  DESCRIPTOR = _FUZZYREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:lib.FuzzyRequest)
  ))
_sym_db.RegisterMessage(FuzzyRequest)

FuzzyReply = _reflection.GeneratedProtocolMessageType('FuzzyReply', (_message.Message,), dict(
  DESCRIPTOR = _FUZZYREPLY,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:lib.FuzzyReply)
  ))
_sym_db.RegisterMessage(FuzzyReply)



_FUZZY = _descriptor.ServiceDescriptor(
  name='Fuzzy',
  full_name='lib.Fuzzy',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=157,
  serialized_end=211,
  methods=[
  _descriptor.MethodDescriptor(
    name='Match',
    full_name='lib.Fuzzy.Match',
    index=0,
    containing_service=None,
    input_type=_FUZZYREQUEST,
    output_type=_FUZZYREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FUZZY)

DESCRIPTOR.services_by_name['Fuzzy'] = _FUZZY

# @@protoc_insertion_point(module_scope)
